version: '3'

services:
    php:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      ports:
          - "8080:80"
      volumes:
        - "./src:/var/www/html"
        - "./config:/usr/local/etc/php"